finalYearProject/admin_app/urls.py
from django.urls import path
from . import views
from .views import addCategory
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',views.adminHome,name="adminHome"),
    path("AdminRegistration/", views.admin_registration, name="AdminRegistration"),
    path("AdminRegistration2/", views.admin_registration2, name="AdminRegistration2"),
    path('updateAdmProfile/<int:id>/',views.updateAdmProfile,name="updateAdmProfile"),
    path('viewAdmProfile/<int:id>/',views.viewAdmProfile,name="viewAdmProfile"),
    path('addCategory/',views.addCategory,name="addCategory"),
    path('updateCategory/<int:id>/',views.updateCategory,name="updateCategory"),
    path('catList/',views.catList,name="catList"),
    path('admList/',views.admList,name="admList"),
    path('updateList/',views.updateList,name="updateList"),
    path('docList/<str:cat>/',views.docList,name="docList"),
    path('ratings/<int:id>',views.ratings,name="ratings"),
    path('banDoc/<int:id>',views.banDoc,name="banDoc"),
    path('adminSearch/',views.adminSearch,name="adminSearch"),
    path('deleteAdmin/<int:id>',views.deleteAdmin,name="deleteAdmin"),
]

finalYearProject/finalYearProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from  account_app.views import landing
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", landing, name="landing"),
    path('account/', include('account_app.urls')),
    path('adminHome/', include('admin_app.urls')),
    path('doctorHome/', include('doctor_app.urls')),
    path('patientHome/', include('patient_app.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finalYearProject/account_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator
import datetime


# Create your models here.

class User(AbstractUser):
    # first_name = models.CharField(max_length=100)
    # last_name = models.CharField(max_length=100)
    # email = models.EmailField(max_length=300)
    header_image = models.ImageField(null=True, blank=True, upload_to='profilePic/')
    middle_name = models.CharField(max_length=100, default='')
    date_of_birth = models.DateField(null=True,blank=True)
    contact_no = models.CharField(max_length=16)
    is_patient = models.BooleanField(default=False)
    is_doctor = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    gender = models.CharField(max_length=10,default='None')

    def calculateAge(self):
        today = datetime.date.today()
        try:
            birthday = self.date_of_birth.replace(year=today.year)

        # raised when birth date is February 29
        # and the current year is not a leap year
        except ValueError:
            birthday = self.date_of_birth.replace(year=today.year,
                                    month=self.date_of_birth.month + 1, day=1)

        if birthday > today:
            return today.year - self.date_of_birth.year - 1
        else:
            return today.year - self.date_of_birth.year


class Patient(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return self.user.first_name


class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    doctor_reg_id = models.CharField(max_length=100,default="-")
    specialization = models.CharField(max_length=100)
    fees = models.IntegerField(max_length=6,default=0)
    experience = models.IntegerField(max_length=2,default=0)
    degrees = models.CharField(max_length=250,default="No degrees Specified")
    degree_certificate = models.FileField(null=True, blank=True, upload_to='degreeCertificate/')
    bio = models.TextField(default="-")
    likes = models.ManyToManyField(Patient, related_name="doctor_likes")
    dislikes = models.ManyToManyField(Patient, related_name="doctor_dislikes")
    chamber_address = models.TextField(default="")

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['doctor_reg_id'], name='unique_doctor_reg_id')
        ]

    def __str__(self):
        return self.user.first_name

    def total_likes(self):
        return self.likes.count()

    def total_dislikes(self):
        return self.dislikes.count()

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return self.user.first_name

finalYearProject/admin_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Specialization(models.Model):
    header_image = models.ImageField(null=True, blank=True, upload_to="imagesSpl/")
    category = models.CharField(max_length=255)
    count = models.IntegerField(default=0)

    def __str__(self):
        return self.category



class BannedUser(models.Model):
    userid = models.CharField(max_length=1000,primary_key=True)

    def __str__(self):
        return self.userid

finalYearProject/account_app/forms.py
from django import forms
from .models import User, Patient, Doctor
from django.contrib.auth.forms import UserCreationForm



class PatientRegistrationForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    middle_name = forms.CharField(required=False)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    contact_no = forms.CharField(required=True)
    header_image = forms.ImageField(required=True)

    class Meta(UserCreationForm.Meta):
        model = User

class DoctorRegistrationForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    middle_name = forms.CharField(required=False)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    contact_no = forms.CharField(required=True)
    fees = forms.IntegerField(required=True)
    experience = forms.IntegerField(required=True)
    degrees = forms.CharField(required=True)
    header_image = forms.ImageField(required=True)
    doctor_reg_id = forms.CharField(required=True)
    degree_certificate = forms.FileField(required=True)
    chamber_address = forms.CharField(widget=forms.Textarea)

    class Meta(UserCreationForm.Meta):
        model = User

class AdminRegistrationForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    middle_name = forms.CharField(required=False)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    contact_no = forms.CharField(required=True)
    header_image = forms.ImageField(required=True)

    class Meta(UserCreationForm.Meta):
        model = User

finalYearProject/admin_app/forms.py
from django import forms
from .models import Specialization


class AddCategoryForm(forms.ModelForm):
    category = forms.CharField(required=True)

    class Meta:
        model = Specialization
        fields=['category','header_image']

finalYearProject/admin_app/views.py
from django.shortcuts import render, redirect
from .forms import AddCategoryForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .models import Specialization, BannedUser
from account_app.models import Doctor, User, Admin
from account_app.forms import AdminRegistrationForm
from patient_app.models import Reviews
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.utils.datastructures import MultiValueDictKeyError
import os
from django.db.models import Q
# Create your views here.

head_spl = Specialization.objects.all()
head_doc = Doctor.objects.all()

@login_required
def adminHome(request):
        return render(request,"adminHome.html", context = {'head_doc':head_doc,'head_spl':head_spl})

def admin_registration(request):
    if request.method == "POST":
        try:
            user = User.objects.get(username=request.POST['username'])
            if user:
                messages.error(request, "User has an account already")
                return redirect('AdminRegistration')
        except User.DoesNotExist:
            request.session["username"]=request.POST['username']
            if request.POST['password1'] == request.POST['password2']:
                request.session["email"] = request.POST['email']
                request.session["password"] = request.POST['password1']
                return HttpResponseRedirect(reverse('AdminRegistration2'))
            else:
                messages.error(request, "Password Mismatch!")
                return HttpResponseRedirect(reverse('AdminRegistration'))
    else:
        form = AdminRegistrationForm()
        return render(request, 'admin_registration.html', {'form': form, 'head_doc':head_doc,'head_spl':head_spl})


def admin_registration2(request):
    if request.method == "POST":
        user = User.objects.create(username=request.session["username"])
        user.email = request.session["email"]
        user.set_password(request.session["password"])
        user.first_name = request.POST['first_name']
        if request.POST['middle_name']:
            user.middle_name = request.POST['middle_name']
        user.last_name = request.POST['last_name']
        user.date_of_birth = request.POST['date_of_birth']
        user.contact_no = request.POST['contact_no']
        user.gender = request.POST['gender']
        user.is_admin = True
        user.is_superuser = True
        user.save()
        admin = Admin.objects.create(user=user)
        admin.save()
        messages.success(request, ("User Created Successfully!"))
        return redirect('AdminRegistration')
    else:
        form = AdminRegistrationForm()
        return render(request, 'admin_registration2.html', {'form': form, 'head_doc':head_doc,'head_spl':head_spl})

@login_required
def updateAdmProfile(request, id):
    user = User.objects.get(pk=id)
    image = user.header_image
    if request.method == "POST":
        user.first_name = request.POST["first_name"]
        user.middle_name = request.POST["middle_name"]
        user.last_name = request.POST["last_name"]
        user.contact_no = request.POST["contact_no"]
        user.email = request.POST["email"]
        user.gender = request.POST["gender"]
        try:
            if request.FILES["header_image"]:
                if image:
                    if os.path.exists(image.path):  # to remove the image source and replace it with the new image
                        os.remove(image.path)
                user.header_image = request.FILES["header_image"]
        except MultiValueDictKeyError:
            if image:
                user.header_image = image
        user.save()
        admin = Admin.objects.get(user=user)
        admin.save()
        messages.error(request, "Your Profile Details have been successfully updated!")
        return HttpResponseRedirect(reverse('viewAdmProfile', args=[id]))
    else:
        return render(request, 'updateAdmProfile.html', context={'user': user, 'head_doc':head_doc,'head_spl':head_spl})

@login_required
def viewAdmProfile(request, id):
    try:
        admin = Admin.objects.get(pk=id)
    except Admin.DoesNotExist:
        return render(request, "dump.html") #dump end
    age = admin.user.calculateAge()
    return render(request, 'viewAdmProfile.html', context={'admin': admin,'age':age, 'head_doc':head_doc,'head_spl':head_spl})


@login_required
def addCategory(request):
    if request.method == "POST":
        form = AddCategoryForm(request.POST, request.FILES) # request.FILES is necessary so that the images can be
        if form.is_valid():                                 # saved in the backend
            form.save()
            messages.success(request, ("Category added successfully!"))
            return redirect('addCategory')
    else:
        form = AddCategoryForm()
        return render(request, 'addCategory.html', context={'form':form,'head_doc':head_doc,'head_spl':head_spl})

@login_required
def updateList(request):
    specialization = Specialization.objects.all().order_by("category")
    paginator = Paginator(specialization, 8)  # to add paging to the website
    count = specialization.count()
    page = request.GET.get('pg')
    all_specialization = paginator.get_page(page)
    return render(request, "updateList.html", context={'specialization': all_specialization,'count':count ,'head_doc':head_doc,'head_spl':head_spl})

@login_required
def catList(request):
    specialization = Specialization.objects.all().order_by("category")
    paginator = Paginator(specialization, 8)  # to add paging to the website
    count = specialization.count()
    page = request.GET.get('pg')
    all_specialization = paginator.get_page(page)
    return render(request, "catList.html", context={'specialization': all_specialization, 'count': count,'head_doc':head_doc,'head_spl':head_spl})

@login_required
def admList(request):
    admin = Admin.objects.all()
    paginator = Paginator(admin, 6)  # to add paging to the website
    count = admin.count()
    page = request.GET.get('pg')
    all_admin = paginator.get_page(page)
    return render(request, "admList.html", context={'admin': all_admin, 'count': count,'head_doc':head_doc,'head_spl':head_spl})


@login_required
def updateCategory(request, id):
        try:
            specialization = Specialization.objects.get(pk=id)
        except Specialization.DoesNotExist:
            return render(request, "dump.html")
        image = specialization.header_image
        if request.method == "POST":
            specialization.category = request.POST["category"]
            try:
                if request.FILES["header_image"]:
                    if image:
                        if os.path.exists(image.path):  # to remove the image source and replace it with the new image
                            os.remove(image.path)
                    specialization.header_image = request.FILES["header_image"]
            except MultiValueDictKeyError:
                if image:
                    specialization.header_image = image
            specialization.save()
            messages.error(request, "Category has been updated successfully!")
            return redirect("updateList")
        else:
            return render(request, "updateCategory.html", context={'spl': specialization,'head_doc':head_doc,'head_spl':head_spl})

@login_required
def docList(request, cat):
    doctor = Doctor.objects.filter(specialization=cat).order_by("user__first_name")
    count = doctor.count()
    paginator = Paginator(doctor, 6)  # to add paging to the website
    page = request.GET.get('pg')
    all_doctor = paginator.get_page(page)
    return render(request, "docList.html", {'doctor': all_doctor, 'count': count, 'head_doc':head_doc,'head_spl':head_spl})

@login_required
def ratings(request, id):
    user = User.objects.get(pk=id)
    try:
        doctor = Doctor.objects.get(user=user)
    except Doctor.DoesNotExist:
        return render(request, "dump.html")
    reviews = Reviews.objects.filter(doctor=doctor)
    count = reviews.count()
    return render(request, "ratings.html", context={'doctor':doctor,'reviews':reviews,'count':count,'head_doc':head_doc,'head_spl':head_spl})

@login_required
def banDoc(request, id): # a function to ban a doctor with a unique doctor reg_id and delete their instance where ever present
    user = User.objects.get(pk=id)
    try:
        doctor = Doctor.objects.get(user=user)
    except Doctor.DoesNotExist:
        return render(request, "dump.html")
    bannedDoc = BannedUser.objects.create(userid=doctor.doctor_reg_id)
    bannedDoc.save()
    doctor.delete()
    return redirect("catList")

def adminSearch(request):
    if request.method == "POST":
        name = request.POST["tags"]
        try:
            specialization = Specialization.objects.get(category=name)  # if the typed word matches exactly with the name of the specialization
            if specialization:
                return HttpResponseRedirect(reverse("docList", args=[name]))
        except Specialization.DoesNotExist:
            try:
                l1 = name.split()
                if len(l1) == 3:
                    first_name = l1[1]
                    last_name = l1[2]
                    doctor = Doctor.objects.get(user__first_name=first_name,
                                                user__last_name=last_name)  # if the word matches with the doctor name
                    if doctor:
                        return HttpResponseRedirect(reverse("ratings", args=[doctor.user.id]))
                else:
                    spl = Specialization.objects.filter(
                        Q(category__icontains=name))  # else generate a list with results containing those set of letters if it exists
                    doc = Doctor.objects.filter(

finalYearProject/admin_app/templates/admin_registration2.html
{% extends "base.html" %}

{% block title %}
    AdminHome
{% endblock title %}

        {% block context %}

            <div class="container-fluid" style="margin-top: -72px;">

     {% if user.is_admin and user.is_staff %}

      <div class="row">
                    <div class="col-12">
                        <div class="card" style="margin:24px;">
                            <div class="card-body">
                                <h4 class="card-title" style="padding-bottom: 30px;">Add Admin</h4>
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-body">
                                        <label for="id_first_name">Name </label>
                                        <div class="row">
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <input type="text" class="form-control" name="first_name" id="id_first_name"
                                                        placeholder="First Name" required>
                                                </div>
                                            </div>
											<div class="col-md-4">
                                                <div class="form-group">
                                                    <input type="text" class="form-control" name="middle_name" id="id_middle_name"
                                                        placeholder="Middle Name">
                                                </div>
											</div>
											<div class="col-md-4">
                                                <div class="form-group">
                                                    <input type="text" class="form-control" name="last_name" id="id_last_name"
                                                        placeholder="Last Name" required>
                                                </div>
											</div>
										</div>
                                    </div>
										<div class="form-body" style="padding-top: 20px;">
                                        <div class="row">
                                            <div class="col-md-4">
												<label for="id_date_of_birth">Date of Birth </label>
                                                <div class="form-group">
                                                    <input type="date" class="form-control" id="id_date_of_birth" name="date_of_birth" required>
                                                </div>
                                            </div>
											<div class="col-md-4">
												<label for="id_contact_no">Contact No</label>
                                                <div class="form-group">
                                                    <input type="text" class="form-control" name="contact_no" id="id_contact_no"
                                                        placeholder="Enter Contact Number" required>
                                                </div>
											</div>
											<div class="col-md-4">
												<label style="padding-bottom: 8px;">Gender</label>
                                                <div class="form-group">
                                                    <div class="form-check form-check-inline">
														<input class="form-check-input" type="radio" name="gender"
															id="inlineRadio1" value="Male" required>
														<label class="form-check-label font-weight-light" for="inlineRadio1">Male</label>
													</div>
													<div class="form-check form-check-inline">
														<input class="form-check-input" type="radio" name="gender"
															id="inlineRadio2" value="Female" required>
														<label class="form-check-label font-weight-light" for="inlineRadio2">Female</label>
													</div>
													<div class="form-check form-check-inline">
														<input class="form-check-input" type="radio" name="gender"
															id="inlineRadio3" value="Others" required>
														<label class="form-check-label font-weight-light" for="inlineRadio3">Others</label>
													</div>
                                                </div>
											</div>
										</div>
                                   </div>
								  <div class="form-actions" style="margin-top: 24px;">
                                        <div class="text-left">
                                            <button type="submit" class="btn btn-info">Submit</button>
                                            <button type="reset" class="btn btn-link">Reset</button>
                                        </div>
                                    </div>
							  </form>
						  </div>
						</div>
					</div>
			</div>

     {% else %}

         <h3>You are not authorized here!</h3>

    {% endif %}

            </div>

    {% endblock context %}

finalYearProject/admin_app/templates/dump.html
{% extends "base.html" %}

{% block title %}
    DumpEnd
{% endblock title %}


        {% block context %}

            <div class="container-fluid">

                <h5>You are not authorized here!</h5>

            </div>

        {% endblock context %}

finalYearProject/admin_app/templates/updateAdmProfile.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Update
{% endblock title %}

{% block context %}

    <div class="container-fluid" style="margin-top: -72px;">

    {% if user.is_authenticated%}

        {% if user.is_admin %}

            {% if user.id == request.user.id %}

             <div class="card">
					<div class="card-body" style="margin-left: 24px; padding-bottom:120px;">
						<h2 class="text-dark font-weight-medium" style="padding-bottom: 80px; padding-top: 24px;">Edit Profile</h2>
						<form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
							<div class="row">
								<div class="form-body">
									<img src="{% if user.header_image %}{{ user.header_image.url }}{% else %}{% static 'images/defaultpic.jpg' %}{% endif %}" alt="user" class="rounded-circle " style="margin: 0 350px;width: 200px;height:200px;">
									<!--<button class="btn btn-outline-light text-dark" style="margin-left:340px; margin-top: 24px;">Change Image</button>-->
                                    <div class="row" style="padding-top: 24px;padding-left:300px;">
                                    <div class="form-group">
                                                   <div class="input-group mb-3">
													 <div class="custom-file">
															<input type="file" class="custom-file-input" name="header_image" id="id_header_image" accept="image/*">
															<label class="custom-file-label" for="id_header_image">Change Profile Picture</label>
													 </div>
												  </div>
                                    </div>
                                    </div>
                                </div>
							</div>
                            <div class="row" style="padding-top: 32px; margin-left:56px;">
                                <div class="form-body">
                                    <label for="id_first_name">Name </label>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <input type="text" class="form-control"
                                                        name="first_name" id="id_first_name" value="{{ user.first_name }}" required>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <input type="text" class="form-control"
                                                    name="middle_name" value="{{ user.middle_name }}" >
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <input type="text" class="form-control"
                                                    name="last_name" value="{{ user.last_name }}" required>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row" style="padding-top: 8px;">
                                        <div class="col-md-6">
                                            <label for="id_email">Email</label>
                                            <div class="form-group">
                                                <input type="email" class="form-control"
                                                    name="email" id="id_email" value="{{ user.email }}" required>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <label for="id_contact_no">Contact</label>
                                            <div class="form-group">
                                                <input type="tel" class="form-control"
                                                    name="contact_no" id="id_contact_no" pattern="[6789]{1}[0-9]{9}" value="{{ user.contact_no }}" required>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="row" style="padding-top: 8px;">

                                        <div class="col-md-6">
                                            <label style="padding-bottom: 8px;">Gender</label>
                                            <div class="form-group">
                                                {% if user.gender == "Male" %}
                                                    <div class="form-check form-check-inline">
                                                        <input class="form-check-input" type="radio" name="gender" id="gender1" value="Male" checked>
                                                        <label class="form-check-label font-weight-light" for="gender1" select>Male</label>
                                                    </div>
                                                {% else %}
                                                    <div class="form-check form-check-inline">
                                                        <input class="form-check-input" type="radio" name="gender" id="gender1" value="Male">
                                                        <label class="form-check-label font-weight-light" for="gender1" select>Male</label>
                                                    </div>
                                                {% endif %}
                                                {% if user.gender == "Female" %}
                                                    <div class="form-check form-check-inline">
                                                        <input class="form-check-input" type="radio" name="gender" id="gender2" value="Female" checked>
                                                        <label class="form-check-label font-weight-light" for="gender2" select>Female</label>
                                                    </div>
                                                {% else %}
                                                    <div class="form-check form-check-inline">
                                                        <input class="form-check-input" type="radio" name="gender" id="gender2" value="Female">
                                                        <label class="form-check-label font-weight-light" for="gender2" select>Female</label>
                                                    </div>
                                                {% endif %}
                                                {% if user.gender == "Others" %}
                                                    <div class="form-check form-check-inline">
                                                        <input class="form-check-input" type="radio" name="gender" id="gender3" value="Others" checked>
                                                        <label class="form-check-label font-weight-light" for="gender3" select>Others</label>
                                                    </div>
                                                {% else %}
                                                    <div class="form-check form-check-inline">
                                                        <input class="form-check-input" type="radio" name="gender" id="gender3" value="Others">
                                                        <label class="form-check-label font-weight-light" for="gender3" select>Others</label>
                                                    </div>
                                                {% endif %}
                                            </div>
                                        </div>

                                    </div>
                                    <div class="form-actions" style="padding-top:16px;">
                                    <div class="text-left">
                                        <button type="submit" class="btn btn-info">Update Details</button>
                                        <!--<button type="reset" class="btn btn-link">Cancel</button>-->
                                    </div>
                                    </div>
                                </div>
                            </div>
						</form>

							</div>
						</div>

            {% else %}

                <h5>You are not authorized here!</h5>

            {% endif %}

    {% else %}

            <h5>You are not authorized here!</h5>

         {% endif %}

    {% endif %}

    </div>

{% endblock context %}