finalYearProject/account_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

urlpatterns = [
    path("PatientRegistration/", views.patient_registration, name="PatientRegistration"),
    path("DoctorRegistration/", views.doctor_registration, name="DoctorRegistration"),
    path("SignUp/", views.signUp, name="signUp"),
    path("PatientSignUp/", views.patient_signup, name="PatientSignUp"),
    path("DoctorSignUp/", views.doctor_signup, name="DoctorSignUp"),
    path("DoctorSignUp2/", views.doctor_signup2, name="DoctorSignUp2"),
    path("login/", auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path('doLogin/', views.doLogin, name="doLogin"),
    path("", auth_views.LogoutView.as_view(), name="logout"),

    #path("reset/", views.reset_views, name="reset"),
    #path("reset2/", views.reset2_views, name="reset2"),

    #Reset Password Urls
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path("password_reset/done/",auth_views.PasswordResetDoneView.as_view(template_name="password_reset_done.html"),name="password_reset_done"),
    path("reset/<uidb64>/<token>/",auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"),name="password_reset_confirm"),
    path("reset/done/",auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"),name="password_reset_complete"),

]

finalYearProject/admin_app/urls.py
from django.urls import path
from . import views
from .views import addCategory
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',views.adminHome,name="adminHome"),
    path("AdminRegistration/", views.admin_registration, name="AdminRegistration"),
    path("AdminRegistration2/", views.admin_registration2, name="AdminRegistration2"),
    path('updateAdmProfile/<int:id>/',views.updateAdmProfile,name="updateAdmProfile"),
    path('viewAdmProfile/<int:id>/',views.viewAdmProfile,name="viewAdmProfile"),
    path('addCategory/',views.addCategory,name="addCategory"),
    path('updateCategory/<int:id>/',views.updateCategory,name="updateCategory"),
    path('catList/',views.catList,name="catList"),
    path('admList/',views.admList,name="admList"),
    path('updateList/',views.updateList,name="updateList"),
    path('docList/<str:cat>/',views.docList,name="docList"),
    path('ratings/<int:id>',views.ratings,name="ratings"),
    path('banDoc/<int:id>',views.banDoc,name="banDoc"),
    path('adminSearch/',views.adminSearch,name="adminSearch"),
    path('deleteAdmin/<int:id>',views.deleteAdmin,name="deleteAdmin"),
]

finalYearProject/finalYearProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from  account_app.views import landing
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", landing, name="landing"),
    path('account/', include('account_app.urls')),
    path('adminHome/', include('admin_app.urls')),
    path('doctorHome/', include('doctor_app.urls')),
    path('patientHome/', include('patient_app.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finalYearProject/account_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator
import datetime


# Create your models here.

class User(AbstractUser):
    # first_name = models.CharField(max_length=100)
    # last_name = models.CharField(max_length=100)
    # email = models.EmailField(max_length=300)
    header_image = models.ImageField(null=True, blank=True, upload_to='profilePic/')
    middle_name = models.CharField(max_length=100, default='')
    date_of_birth = models.DateField(null=True,blank=True)
    contact_no = models.CharField(max_length=16)
    is_patient = models.BooleanField(default=False)
    is_doctor = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    gender = models.CharField(max_length=10,default='None')

    def calculateAge(self):
        today = datetime.date.today()
        try:
            birthday = self.date_of_birth.replace(year=today.year)

        # raised when birth date is February 29
        # and the current year is not a leap year
        except ValueError:
            birthday = self.date_of_birth.replace(year=today.year,
                                    month=self.date_of_birth.month + 1, day=1)

        if birthday > today:
            return today.year - self.date_of_birth.year - 1
        else:
            return today.year - self.date_of_birth.year


class Patient(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return self.user.first_name


class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    doctor_reg_id = models.CharField(max_length=100,default="-")
    specialization = models.CharField(max_length=100)
    fees = models.IntegerField(max_length=6,default=0)
    experience = models.IntegerField(max_length=2,default=0)
    degrees = models.CharField(max_length=250,default="No degrees Specified")
    degree_certificate = models.FileField(null=True, blank=True, upload_to='degreeCertificate/')
    bio = models.TextField(default="-")
    likes = models.ManyToManyField(Patient, related_name="doctor_likes")
    dislikes = models.ManyToManyField(Patient, related_name="doctor_dislikes")
    chamber_address = models.TextField(default="")

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['doctor_reg_id'], name='unique_doctor_reg_id')
        ]

    def __str__(self):
        return self.user.first_name

    def total_likes(self):
        return self.likes.count()

    def total_dislikes(self):
        return self.dislikes.count()

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return self.user.first_name

finalYearProject/account_app/forms.py
from django import forms
from .models import User, Patient, Doctor
from django.contrib.auth.forms import UserCreationForm



class PatientRegistrationForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    middle_name = forms.CharField(required=False)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    contact_no = forms.CharField(required=True)
    header_image = forms.ImageField(required=True)

    class Meta(UserCreationForm.Meta):
        model = User

class DoctorRegistrationForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    middle_name = forms.CharField(required=False)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    contact_no = forms.CharField(required=True)
    fees = forms.IntegerField(required=True)
    experience = forms.IntegerField(required=True)
    degrees = forms.CharField(required=True)
    header_image = forms.ImageField(required=True)
    doctor_reg_id = forms.CharField(required=True)
    degree_certificate = forms.FileField(required=True)
    chamber_address = forms.CharField(widget=forms.Textarea)

    class Meta(UserCreationForm.Meta):
        model = User

class AdminRegistrationForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    middle_name = forms.CharField(required=False)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    contact_no = forms.CharField(required=True)
    header_image = forms.ImageField(required=True)

    class Meta(UserCreationForm.Meta):
        model = User

finalYearProject/account_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import PatientRegistrationForm, DoctorRegistrationForm
from .models import User, Patient, Doctor
from patient_app.models import Appointment
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail, BadHeaderError
from django.contrib.auth.forms import PasswordResetForm
from .models import User
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from finalYearProject.settings import EMAIL_HOST_USER
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from admin_app.models import Specialization, BannedUser
import matplotlib
matplotlib.use('Agg')
from matplotlib import pyplot as plt
import datetime
import base64
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile


# Create your views here.

def make_autopct(values):
    def my_autopct(pct):
        total = sum(values)
        val = int(round(pct * total / 100.0))
        return '{p:.2f}%  ({v:d})'.format(p=pct, v=val)
    return my_autopct

def landing(request):
    doctor = Doctor.objects.all()
    doctor_count = doctor.count
    patient = Patient.objects.all()
    patient_count = patient.count
    appointment_count = Appointment.objects.all().count

    # labels = '',''

    plist = list(patient.values())
    dlist = list(doctor.values())

    total_users = len(plist) + len(dlist)
    # sample = 60
    # non_users = sample-total_users
    #
    # sizes = [total_users,non_users]
    #
    # users = ['Registered','Not registered']
    #
    # colors = [ '#f5f595' ,  '#66b3ff',  '#99ff99']
    # explode = (0.1,0)  # only "explode" the 2nd slice (i.e. 'Hogs')
    #
    # fig1, ax1 = plt.subplots( subplot_kw=dict(aspect="equal"))  #figsize to set horizontal and vertical distance of pie
    #
    #
    # wedges,text,autotext = ax1.pie(sizes, explode=explode, labels=labels, colors=colors, autopct=make_autopct(sizes), textprops=dict(color="k"),shadow=True, startangle=90)
    #
    # ax1.set_title("Growing users")
    # ax1.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
    #
    # ax1.legend(wedges, users,title="Users",loc="center left",bbox_to_anchor=(0.80, 0.75, 0.5, 0.25))
    #
    # plt.setp(autotext, size=8, weight="bold")
    #
    # plt.savefig('media/users_piechart.png', dpi=100)

    return render(request, 'landing.html', context={'total_users':total_users, 'doctor_count':doctor_count, 'patient_count':patient_count, 'appointment_count':appointment_count})

def doLogin(request):
    if request.method != "POST":
        return HttpResponse("<h2>Method Not Allowed</h2>")
    else:
        user = authenticate(username=request.POST["username"], password=request.POST["password"])
        if user:
            login(request, user)
            if user.is_admin:
                return redirect('adminHome')
            elif user.is_patient:
                return redirect('patientHome')
            else:
                return HttpResponseRedirect(reverse('doctorHome', args=[user.id]))
        else:
            messages.error(request, "Invalid Credentials")
            return redirect('login')

def signUp(request):
    return render(request, "signUp.html")


def patient_registration(request):
    if request.method == "POST":
        try:
            user = User.objects.get(username=request.POST['username'])
            if user:
                messages.error(request, "User has an account already")
                return redirect('PatientRegistration')
        except User.DoesNotExist:
            request.session["username"]=request.POST['username']
            if request.POST['password1'] == request.POST['password2']:
                try:
                    validate_email(request.POST['email'])
                except ValidationError as e:
                    messages.error(request, ("Bad Email"))
                    return redirect('PatientRegistration')
                request.session["email"] = request.POST['email']
                request.session["password"] = request.POST['password1']
                return HttpResponseRedirect(reverse('PatientSignUp'))
            else:
                messages.error(request, "Password Mismatch!")
                return HttpResponseRedirect(reverse('PatientRegistration'))
    else:
        form = PatientRegistrationForm()
        return render(request, 'patient_registration1.html', {'form': form})


def patient_signup(request):
    if request.method == "POST":
        user = User.objects.create(username=request.session["username"])
        user.email = request.session["email"]
        user.set_password(request.session["password"])
        user.first_name = request.POST['first_name']
        if request.POST['middle_name']:
            user.middle_name = request.POST['middle_name']
        user.last_name = request.POST['last_name']
        user.date_of_birth = request.POST['date_of_birth']
        user.contact_no = request.POST['contact_no']
        user.gender = request.POST['gender']
        user.is_patient = True
        user.save()
        patient = Patient.objects.create(user=user)
        patient.save()
        messages.success(request, ("User Created Successfully!"))
        return redirect('patientHome')
    else:
        form = PatientRegistrationForm()
        return render(request, 'patient_signup.html', {'form': form})


def doctor_registration(request):
    if request.method == "POST":
        try:
            user = User.objects.get(username=request.POST['username'])
            if user:
                messages.error(request, "User with this username has an account already")
                return redirect('DoctorRegistration')
        except User.DoesNotExist:
            try:
                doctor = Doctor.objects.get(doctor_reg_id=request.POST['doctor_reg_id'])
                if doctor:
                    messages.error(request, "User with this registration id has an account already")
                    return redirect('DoctorRegistration')
            except Doctor.DoesNotExist:
                try:
                    banDoc = BannedUser.objects.get(userid=request.POST["doctor_reg_id"])
                    if banDoc:
                        messages.error(request, "You have been banned. So,you cannot SignUp!")
                        return redirect('DoctorRegistration')
                except BannedUser.DoesNotExist:
                    request.session["username"] = request.POST['username']
                    if request.POST['password1'] == request.POST['password2']:
                        try:
                            validate_email(request.POST['email'])
                        except ValidationError as e:
                            messages.error(request, ("Bad Email"))
                            return redirect('DoctorRegistration')
                        request.session["email"] = request.POST['email']
                        request.session["password"] = request.POST['password2']
                        request.session["reg_id"] = request.POST["doctor_reg_id"]

                        image = request.FILES['header_image']

                        # encoding image to byte64 string to store in session
                        request.session['header_image'] = base64.b64encode(image.read()).decode()

                        # code to retrieve name of the image file
                        image = str(image).split(".")
                        request.session['image_name'] = image[0]

                        return redirect('DoctorSignUp')
                    else:
                        messages.error(request, "Password Mismatch!")
                        return redirect('DoctorRegistration')
    else:
        form = DoctorRegistrationForm()
        return render(request, 'doctor_registration1.html', {'form': form})


def doctor_signup(request):
    if request.method == "POST":
        request.session["first_name"] = request.POST['first_name']
        if request.POST['middle_name']:
            request.session["middle_name"] = request.POST['middle_name']
        else:
            request.session["middle_name"]=""
        request.session["last_name"] = request.POST['last_name']
        request.session["contact_no"] = request.POST['contact_no']
        request.session["gender"] = request.POST['gender']
        request.session["date_of_birth"] = request.POST['date_of_birth']
        request.session["sp"] = request.POST['sp']
        return redirect('DoctorSignUp2')
    else:
        form = DoctorRegistrationForm()
        specialization = Specialization.objects.all()
        return render(request, 'doctor_signup.html', {'form': form, 'specialization': specialization})

def doctor_signup2(request):
    if request.method == "POST":
        user = User.objects.create(username=request.session["username"])
        user.email = request.session["email"]
        user.set_password(request.session["password"])
        user.first_name = request.session['first_name']
        if request.session['middle_name']!="":
            user.middle_name = request.session['middle_name']
        user.last_name = request.session['last_name']
        user.contact_no = request.session['contact_no']
        user.gender = request.session['gender']

        #decoding the string to image again and then using InMemoryUploadedFile to save it into the database
        image = request.session['header_image']
        data = base64.b64decode(image.encode('UTF-8'))
        buf = BytesIO(data)
        img = Image.open(buf)

finalYearProject/account_app/templates/doctor_signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="fonts/material-icon/css/material-design-iconic-font.min.css">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">

    <!-- google font -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,700,800' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>


</head>
<body>

    <div class="main">
        <!-- Sign up form -->
        <section class="signup">
            <div class="container">
                <div class="error-msg" style="padding-top: 50px; margin: 0 50px -100px;">
                    {% if messages %}
                        {% for messages in messages %}
                            <div class="alert alert-danger alert-dismissable fade show">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                {{ messages }}
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="signup-content">
                    <div class="signup-form">
                        <h2 class="form-title">Sign up</h2>
                        <form method="POST" class="register-form" id="register-form">
                            {% csrf_token %}
							<!--<div class="form-group file-select-button">
								<label >Upload your Profile Picture:</label>
							  <p style="width: 100%; color: #222;font-size: 15px; font-weight: 500; padding-bottom: 5px;">Upload Profile Picture</p>
								<input type="file" name="file">
						  	</div>-->
                            <div class="form-group">
                                <label for="id_first_name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="text" name="first_name" id="id_first_name" placeholder="First Name" required/>
                            </div>
                            <div class="form-group">
                                <label for="id_middle_name"><i class="zmdi zmdi-email"></i></label>
                                <input type="text" name="middle_name" id="id_middle_name" placeholder="Middle Name"/>
                            </div>
                            <div class="form-group">
                                <label for="id_last_name"><i class="zmdi zmdi-lock"></i></label>
                                <input type="text" name="last_name" id="id_last_name" placeholder="Last Name" required/>
                            </div>
                            <div class="form-group">
                                <label for="id_date_of_birth"><i class="zmdi zmdi-lock-outline"></i></label>
                                <input type="date" name="date_of_birth" id="id_date_of_birth" required/>
                            </div>
                            <div class="form-group">
                                <label for="id_contact_no"><i class="zmdi zmdi-lock-outline"></i></label>
                                <input type="text" name="contact_no" id="id_contact_no" pattern="[6789]{1}[0-9]{9}" placeholder="Contact Number" required/>
                            </div>
                            <div class="form-group gender">
								<p class="label--block">Gender</p>
								<div style="padding-top: 20px;" >
									<label class="radio-container">Male
										<input type="radio" name="gender" value="Male" required>
										<span class="checkmark"></span>
									</label>
									<label class="radio-container">Female
										<input type="radio" name="gender" value="Female" required>
										<span class="checkmark"></span>
									</label>
									<label class="radio-container">Others
										<input type="radio" name="gender" value="Others" required>
										<span class="checkmark"></span>
									</label>
								</div>
							</div>
							<div class="form-group" style="border: none;">
                                    <select name="sp" id="inlineFormCustomSelect" class="custom-select mr-sm-2" required>

                                        <option selected>Choose Specialisation</option>

                                            {% for specialization in specialization %}
                                            <option value="{{ specialization }}">{{ specialization }}</option>
                                        {% endfor %}
                                    </select>
                        	</div>
							<div class="form-group form-button">
                                <input type="submit" name="signup" id="signup" class="form-submit" value="Next"/>
                            </div>
                        </form>
                    </div>
                    <div class="signup-image">
                        <figure><img src="{% static 'images/Medicine-cuate.svg' %}"></figure>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- JS -->
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

finalYearProject/account_app/templates/doctor_signup2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="fonts/material-icon/css/material-design-iconic-font.min.css">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">

    <!-- google font -->
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,700,800' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>


</head>
<body>

    <div class="main">
        <!-- Sign up form -->
        <section class="signup">
            <div class="container">
                <div class="error-msg" style="padding-top: 50px; margin: 0 50px -100px;">
                    {% if messages %}
                        {% for messages in messages %}
                            <div class="alert alert-danger alert-dismissable fade show">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                {{ messages }}
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="signup-content">
                    <div class="signup-form">
                        <h2 class="form-title">Sign up</h2>
                        <form method="POST" class="register-form" id="register-form" enctype="multipart/form-data">
                            {% csrf_token %}
						  <div class="form-group">
                                <label for="id_fees"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="number" name="fees" id="id_fees" placeholder="Fees" required/>
                            </div>
						  <div class="form-group">
                                <label for="id_experience"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="number" name="experience" id="id_experience" placeholder="Experience (in years)" required/>
                            </div>
                            <div class="form-group">
                                <label for="id_degrees"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="text" name="degrees" id="id_degrees" placeholder="Degrees" required/>
                            </div>
							<!--<div class="form-group">
							    <form class="dp">
								<div class="file-upload-wrapper" data-text="Upload Degree Certificate" style="margin-top: 10px;">
								  <input name="degree_certificate" id="id_degree_certificate" type="file" class="file-upload-field" required value="">
								</div>
							  </form>

							</div>-->
                            <div class="custom-file" style="margin-top: 45px;">
                                <label class="custom-file-label text-left" for="id_header_image" id="file">Upload Degree Certificate</label>
                                <input name="degree_certificate" id="id_degree_certificate" type="file" class="custom-file-input" value="" required>
                            </div>
							<div class="form-group">
                                <label for="id_chamber_address"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <!--<input type="text" name="chamber_address" id="id_chamber_address" placeholder="Chamber Address" required/>-->
                                <br>
                                <textarea name="chamber_address" id="id_chamber_address" row="10" cols="50" placeholder="Chamber Address" required></textarea>
                            </div>
							<div class="form-group form-button">
                                <input type="submit" name="signup" id="signup" class="form-submit" value="Submit"/>
                            </div>
                        </form>
                    </div>
                    <div class="signup-image">
                        <figure><img src="{% static 'images/Medicine-cuate.svg' %}"></figure>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <script type="text/javascript">
        $('#id_degree_certificate').on("change",function() {
      console.log("change fire");
     var i = $(this).prev('label').clone();
      var file = $('#id_degree_certificate')[0].files[0].name;
   console.log(file);
      $(this).prev('label').text(file);

    });
    </script>

    <!-- JS -->
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

finalYearProject/account_app/templates/password_reset.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Forgot Password</title>

    <!-- Font Icon
    <link rel="stylesheet" href="{% static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">-->

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/fp.css' %}">

    <!-- google font -->
		<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,700,800' rel='stylesheet' type='text/css'>

</head>
<body>

    <div class="main">
        <!-- Forgot Password  Form -->
        <section class="fp">
            <div class="container">
                <div class="fp-content">
                    <div class="fp-image">
					  <figure><img src="{% static 'images/fp-image.png' %}" alt="sing up image"></figure>
                    </div>

                    <div class="fp-form">
                        <h2 class="form-title">Forgot Password?</h2>
                        <form method="POST" class="register-form" id="login-form">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="username"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="text" name="username" id="username" placeholder="Username" required/>
                            </div>
                            <div class="form-group form-button">
                                <input type="submit" name="fp" id="fp" class="form-submit" value="Send E-mail"/>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>

    </div>

    <!-- JS -->
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

finalYearProject/account_app/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

      <a href="{% url 'PatientRegistration' %}">Patient Sign Up</a>
      <a href="{% url 'DoctorRegistration' %}">Doctor Sign Up</a>

</body>
</html>