finalYearProject/admin_app/urls.py
from django.urls import path
from . import views
from .views import addCategory
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',views.adminHome,name="adminHome"),
    path("AdminRegistration/", views.admin_registration, name="AdminRegistration"),
    path("AdminRegistration2/", views.admin_registration2, name="AdminRegistration2"),
    path('updateAdmProfile/<int:id>/',views.updateAdmProfile,name="updateAdmProfile"),
    path('viewAdmProfile/<int:id>/',views.viewAdmProfile,name="viewAdmProfile"),
    path('addCategory/',views.addCategory,name="addCategory"),
    path('updateCategory/<int:id>/',views.updateCategory,name="updateCategory"),
    path('catList/',views.catList,name="catList"),
    path('admList/',views.admList,name="admList"),
    path('updateList/',views.updateList,name="updateList"),
    path('docList/<str:cat>/',views.docList,name="docList"),
    path('ratings/<int:id>',views.ratings,name="ratings"),
    path('banDoc/<int:id>',views.banDoc,name="banDoc"),
    path('adminSearch/',views.adminSearch,name="adminSearch"),
    path('deleteAdmin/<int:id>',views.deleteAdmin,name="deleteAdmin"),
]

finalYearProject/finalYearProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from  account_app.views import landing
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", landing, name="landing"),
    path('account/', include('account_app.urls')),
    path('adminHome/', include('admin_app.urls')),
    path('doctorHome/', include('doctor_app.urls')),
    path('patientHome/', include('patient_app.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finalYearProject/patient_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',views.patientHome,name="patientHome"),
    path('updatePatProfile/<int:id>/',views.updatePatProfile,name="updatePatProfile"),
    path('viewPatProfile/<int:id>/',views.viewPatProfile,name="viewPatProfile"),
    path('category/<str:cat>/',views.categoryList,name="categoryList"),
    path('specializationList/',views.specializationList,name="specializationList"),
    path('checkDocProfile/<int:id>/',views.checkDocProfile,name="checkDocProfile"),
    path('bookAppointment/<int:id>/<int:patid>/',views.bookAppointment,name="bookAppointment"),
    path('patientInfo/',views.patientInfo,name="patientInfo"),
    path('currentApp/<int:id>/',views.currentApp,name="currentApp"),
    path('patCancelAppointment/<int:id>/',views.patCancelAppointment,name="patCancelAppointment"),
    path('patCancelAppointment1/<int:id>/',views.patCancelAppointment1,name="patCancelAppointment1"),
    path('historyApp/<int:id>/',views.historyApp,name="historyApp"),
    path('cancelledApp/<int:id>/',views.cancelledApp,name="cancelledApp"),
    path('likeDoc/<int:id>/<int:patid>/',views.likeDoc,name="likeDoc"),
    path('dislikeDoc/<int:id>/<int:patid>/',views.dislikeDoc,name="dislikeDoc"),
    path('giveReview/<int:id>/',views.giveReview,name="giveReview"),
    path('getResult/',views.getResult,name="getResult"),
    path('deletePicture/<int:id>/',views.deletePicture,name="deletePicture"),
    path('documentUpload/<int:id>/',views.documentUpload,name="documentUpload"),
    path('removeDocument/<int:id>/',views.removeDocument,name="removeDocument"),
    path('removeDocument1/<int:id>/<int:patid>/',views.removeDocument1,name="removeDocument1"),
]

finalYearProject/patient_app/models.py
from django.db import models
from account_app.models import Doctor, Patient

# Create your models here.

CHOICES = (('12:00', '12:00'),('13:00', '13:00') , ('14:00', '14:00') , ('15:00', '15:00') ,('16:00', '16:00') ,('17:00', '17:00'), ('18:00', '18:00') )


class Appointment(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, default=None)
    a_date = models.CharField(max_length=25)
    a_time = models.CharField(choices=CHOICES,max_length=10)
    p_first_name = models.CharField(max_length=100)
    p_middle_name = models.CharField(max_length=100)
    p_last_name = models.CharField(max_length=100)
    p_gender = models.CharField(max_length=10)
    p_contact_no = models.CharField(max_length=10)
    p_email = models.EmailField()
    p_age = models.IntegerField(default=0,blank=False,null=False)
    visit_reason = models.CharField(max_length=50)
    is_cancelled = models.BooleanField(default=False)
    is_marked = models.BooleanField(default=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['a_date', 'a_time', 'doctor'], name='unique_appointment_key')
        ]

    def __str__(self):
        return self.doctor.user.first_name + ' ' + self.doctor.user.last_name + ' ' + str(self.a_date) + ' ' + str(self.a_time)


class Reviews(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    review = models.TextField()

    def __str__(self):
        return 'Review for '+ self.doctor.user.first_name+' '+self.doctor.user.last_name



class DocumentUpload(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    p_name = models.CharField(max_length=120)
    document_name = models.CharField(max_length=120)
    document = models.FileField(null=True, blank=True, upload_to='documentUpload/')

    def __str__(self):
        return self.p_name + " " + self.document_name

finalYearProject/patient_app/forms.py
from django import forms
from .models import Appointment, Reviews, DocumentUpload

class AppointmentForm(forms.ModelForm):


    p_middle_name = forms.CharField(required=False)
    visit_reason =  forms.CharField(required=False)

    class Meta:
        model = Appointment
        #fields = ['p_first_name', 'p_middle_name', 'p_last_name', 'p_contact_no', 'p_email' , 'p_age', 'a_time', 'visit_reason']
        fields = ['a_time','a_date']


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Reviews
        fields = ['review']

class DocumentUplaodForm(forms.ModelForm):

    class Meta:
        model = DocumentUpload
        fields = ['p_name','document_name','document']

finalYearProject/patient_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from account_app.models import User, Patient, Doctor
from django.urls import reverse
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from admin_app.models import Specialization
from .forms import AppointmentForm, ReviewForm, DocumentUplaodForm
import datetime
from patient_app.models import Appointment, Reviews, DocumentUpload
from finalYearProject.settings import EMAIL_HOST_USER
from django.core.mail import send_mail, BadHeaderError
from django.core.paginator import Paginator
from django.utils.datastructures import MultiValueDictKeyError
import os
from django.db.models import Q
import requests

# Create your views here.
url = "https://www.fast2sms.com/dev/bulkV2"
headers = {
        'cache-control': "no-cache"
    }

def sendSms(message,contact_no):
    ###############

    querystring = {
        "authorization": "x2eVImBiDW9ko54XK1F7AzjfgtPcJTpQryCvNhubR6UsYGEq0OQ6dqMmGhACeas2ONwo8l0DXtL7iyB4",
        "message": message,
        "language": "english",
        "route": "q",
        "numbers": contact_no}

    try:
        response = requests.request("GET", url,
                                    headers=headers,
                                    params=querystring)
        print("SMS Successfully Sent")
    except:
        print("Oops! Something wrong")

    ###################### SMS CHUNK

head_spl = Specialization.objects.all()
head_doc = Doctor.objects.all()


@login_required
def patientHome(request): #dynamic list that changes on the increasing demand of the specialization
    specialization = Specialization.objects.raw("select * from admin_app_specialization order by count desc limit 6")
    return render(request, "patientHome.html",context={'specialization':specialization,'head_spl':head_spl,'head_doc':head_doc})

@login_required
def specializationList(request):
    specialization = Specialization.objects.all().order_by("category")
    paginator = Paginator(specialization, 8)  # to add paging to the website
    count = specialization.count()
    page = request.GET.get('pg')
    all_specialization = paginator.get_page(page)
    return render(request, "specializationList.html", context={'specialization':all_specialization,'count':count, 'head_spl':head_spl,'head_doc':head_doc})

@login_required
def updatePatProfile(request, id):
    user = User.objects.get(pk=id)
    image = user.header_image
    if request.method == "POST":
        user.first_name = request.POST["first_name"]
        user.middle_name = request.POST["middle_name"]
        user.last_name = request.POST["last_name"]
        user.contact_no = request.POST["contact_no"]
        user.email = request.POST["email"]
        user.gender = request.POST["gender"]
        try:
            if request.FILES["header_image"]:
                if image:
                    if os.path.exists(image.path):  # to remove the image source and replace it with the new image
                        os.remove(image.path)
                user.header_image = request.FILES["header_image"]
        except MultiValueDictKeyError:
            if image:
                user.header_image = image
        user.save()
        patient = Patient.objects.get(user=user)
        patient.save()
        messages.error(request, "Your Profile Details have been successfully updated!")

        return HttpResponseRedirect(reverse('viewPatProfile', args=[id]))
    else:
        return render(request, 'updatePatProfile.html', context={'user': user, 'head_spl':head_spl,'head_doc':head_doc})

@login_required
def viewPatProfile(request, id):
    try:
        patient = Patient.objects.get(pk=id)
    except Patient.DoesNotExist:
        return render(request, "dump.html") #dump end
    age = patient.user.calculateAge()
    return render(request, 'viewPatProfile.html', context={'patient': patient,'age':age, 'head_spl':head_spl,'head_doc':head_doc})

@login_required
def categoryList(request,cat):
    doctor = Doctor.objects.filter(specialization=cat).order_by("user__first_name")
    count = doctor.count()
    paginator = Paginator(doctor, 5)  # to add paging to the website
    page = request.GET.get('pg')
    all_doctor = paginator.get_page(page)
    return render(request,"categoryList.html",{'doctor':all_doctor, 'count':count, 'head_spl':head_spl,'head_doc':head_doc,'cat':cat})

@login_required
def checkDocProfile(request, id):
    doctor = Doctor.objects.get(pk=id)
    total_likes = doctor.total_likes() # function to get total likes from the model directly
    patient = Patient.objects.get(pk=request.user.id)

    # filtering the records on basis of the previous appointments
    present_date = datetime.date.today()

    previous_date = present_date - datetime.timedelta(1)  # to get the previous day date
    previous_date = previous_date.strftime("%Y-%m-%d")

    appointment = Appointment.objects.filter(doctor=doctor,patient=patient,a_date__lt = present_date, is_cancelled=False, is_marked=True) | Appointment.objects.filter(doctor=doctor,patient=patient,a_date__lt = previous_date, is_cancelled=False)

    # to check if the patient has liked the doctor or not
    has_likes = Doctor.objects.filter(likes=patient)
    has_dislikes = Doctor.objects.filter(dislikes=patient)

    #reviews list
    reviews = Reviews.objects.filter(doctor=doctor)
    count = reviews.count()

    return render(request, 'checkDocProfile.html', context={'doctor': doctor, 'total_likes':total_likes, 'appointment':appointment, 'has_likes':has_likes, 'has_dislikes':has_dislikes, 'reviews':reviews, 'count':count, 'head_spl':head_spl,'head_doc':head_doc})

@login_required
def bookAppointment(request, id, patid):
    try:
        doctor = Doctor.objects.get(pk=id)
    except Doctor.DoesNotExist:
        return render(request, "dump.html")
    try:
        patient = Patient.objects.get(pk=patid)
    except Patient.DoesNotExist:
        return render(request, "dump.html")
    if request.method == "POST":
        p_date = request.POST["ad"] #taking date in dd-mm-yyyy format and converting it into yyyy-mm-dd
        p_date = datetime.datetime.strptime(p_date, '%d-%m-%Y')
        p_date = p_date.strftime("%Y-%m-%d")
        p_time = request.POST["a_time"]
        try:
            #if appointment exists with the chosen date and time then a different slot has to be chosen
            appointment = Appointment.objects.get(doctor=doctor, a_date=p_date, a_time=p_time)
            if appointment:
                messages.error(request, "Please choose a different slot for Doctor's Appointment!")
                return HttpResponseRedirect(reverse('bookAppointment', args=[id,patid]))
        except Appointment.DoesNotExist:
            #appointment = Appointment.objects.create(doctor=doctor, a_date=p_date, a_time=p_time, patient=patient)
            request.session["p_date"] = p_date
            request.session["p_time"] = p_time
            request.session["docid"] = id
            request.session["patid"] = patid
            #appointment.save()
            return redirect('patientInfo')
    else:
        form = AppointmentForm()
        present_date = datetime.date.today()
        date_choices = []
        for i in range(1, 8): # function to take only the next seven days of the week
            days = datetime.timedelta(i)
            new_date = present_date + days
            date_choices.append(new_date.strftime("%d-%m-%Y"))
        return render(request, "bookAppointment.html", {'form': form, 'a_date': date_choices, 'doctor': doctor, 'patient':patient, 'head_spl':head_spl,'head_doc':head_doc})

#decide = False

@login_required
def patientInfo(request):
    try:
        doctor = Doctor.objects.get(pk=request.session["docid"])
    except Doctor.DoesNotExist:
        return render(request, "dump.html")
    try:
        patient = Patient.objects.get(pk=request.session["patid"])
    except Patient.DoesNotExist:
        return render(request, "dump.html")
    if request.method == "POST":
        p_date = request.session["p_date"]
        p_time = request.session["p_time"]
        appointment = Appointment.objects.create(doctor=doctor,a_date=p_date,a_time=p_time,patient=patient)
        appointment.p_age = request.POST["p_age"]
        appointment.p_email = request.POST["p_email"]
        appointment.p_first_name = request.POST["p_first_name"]
        appointment.p_last_name = request.POST["p_last_name"]
        appointment.p_gender = request.POST["gender"]
        appointment.p_contact_no = request.POST["p_contact_no"]
        if request.POST["p_middle_name"] != "":
            appointment.p_middle_name = request.POST["p_middle_name"]
        if request.POST["visit_reason"] != "":
            appointment.visit_reason = request.POST["visit_reason"]
        spl = Specialization.objects.get(category = appointment.doctor.specialization)
        spl.count = spl.count + 1 # increase in count = increase in demand of that specialization
        spl.save()
        appointment.save()

        subject = 'Appointment Booking Confirmation for Dr.'+' '+doctor.user.first_name+' '+doctor.user.last_name
        message = 'Your Booking has been Confirmed for Dr.'+' '+doctor.user.first_name+' '+doctor.user.last_name+'.\n\n'+\
                  'Patient Name: '+appointment.p_first_name+' '
        if appointment.p_middle_name:
            message+=appointment.p_middle_name

        message+=' '+appointment.p_last_name+'\n'+\
                  'Appointment Date: '+appointment.a_date+'\n'+\
                  'Appointment Time: '+appointment.a_time+'\n'+'Doctor Chamber Information: \n' +doctor.chamber_address +'\n\n' \
                        +'For any further changes to your appointment contact our customer support at the details given below:-'+'\n\n'+\
                  'Email Id: '+ EMAIL_HOST_USER

finalYearProject/patient_app/templates/documentUpload.html
{% extends "base.html" %}

{% block title %}
    View
{% endblock title %}

{% block context %}

    <div class="container-fluid" style="margin-top:-72px;">

    {% if user.is_authenticated %}

        {% if user.is_patient and request.user.id == user.id %}

            {% if messages %}
            {% for messages in messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                 {{messages}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true" style="color: #1b9e64">&times;</span>
                </button>
            </div>
            {% endfor %}
            {% endif %}

				 <div class="card" style="padding: 16px;">
                            <div class="card-body">
                                <h4 class="card-title" style="padding-bottom: 30px;">Upload Documents</h4>
                                <form method="post" enctype="multipart/form-data" style="margin-left: 24px;">
                                    {% csrf_token %}
                                    <div class="form-body" >
                                        <label for="id_p_name">Patient Name</label>
                                        <div class="row">
                                              <div class="form-group">
                                                    <input type="text" class="form-control" name="p_name" id="id_p_name" maxlength="120"
                                                        placeholder="Enter Patient Name" required>
                                                </div>
										</div>
								    </div>

                                    <div class="form-body" >
                                        <label for="id_document_name">Document Name</label>
                                        <div class="row">
                                            <div class="form-group">
                                                <input type="text" class="form-control" name="document_name" id="id_document_name" maxlength="120"
                                                    placeholder="Enter Document Name" required>
                                            </div>
                                        </div>
                                    </div>

									<div class="form-body">
                                        <label for="id_document">Document</label>
                                        <div class="row">
                                                <div class="form-group">
                                                   <div class="input-group mb-3">
													 <div class="custom-file">
                                                        <label class="custom-file-label text-left" for="id_document" id="file">Upload Document</label>
                                                        <input type="file" class="custom-file-input" name="document" id="id_document" required>
                                                    </div>

                                                       <script type="text/javascript">
                                                            $('#id_document').on("change",function() {
                                                                  console.log("change fire");
                                                                 var i = $(this).prev('label').clone();
                                                                  var file = $('#id_document')[0].files[0].name;
                                                               console.log(file);
                                                                  $(this).prev('label').text(file);

                                                                });

                                                        </script>
												  </div>
											</div>
										</div>
									</div>
								    <div class="form-actions" style="margin-top: 24px;">
                                        <div class="text-left">
                                            <button type="submit" class="btn btn-info">Submit</button>
                                            <button type="reset" class="btn btn-link">Reset</button>
                                        </div>
                                    </div>
							  </form>
					 </div>
				</div>

                {% if list %}

				<div class="card">
					<div class="card-body">
						<h3 class="card-title mt-5"><i
                                        class="mr-1 font-18 mdi mdi-numeric-1-box-multiple-outline" style="padding-top: -20px;"></i>Document List</h3>
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th scope="col">Patient Name</th>
                                                <th scope="col">Document Name</th>
                                                <th scope="col" style="align-content :center;">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for list in list %}
                                            <tr>
                                                <td>{{ list.p_name }}</td>
                                                <td>{{ list.document_name }}</td>
                                                <td><a href="{{ list.document.url }}" target="_blank" rel="noopener noreferrer"><button class="btn btn-link" style="color: green; font-size: 16px;">View</button></a><br><a href="{% url 'removeDocument' list.id %}"><button class="btn btn-link" style="color: red; font-size: 16px;">Remove</button></a></td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                  </table>
                      </div>
				  </div>
				</div>

                 {% else %}

                    No Documents Uploaded

                {% endif %}

        {% else %}

            <h5>You are not authorized here!</h5>

        {% endif %}

    {% endif %}



    </div>

{% endblock context %}

finalYearProject/patient_app/templates/patientInfo.html
{% extends "base.html" %}

{% block title %}
    Update
{% endblock title %}

{% block context %}

    <div class="container-fluid" style="margin-top: -72px">

    {% if user.is_authenticated%}

        {% if user.is_patient %}

            {% if messages %}
    {% for messages in messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
         {{messages}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true" style="color: #1b9e64">&times;</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}


                         <div class="card">
						<div class="card-body" style="margin-left: 32px; padding-bottom:80px;">
							<div class="row">
								<h2 class="text-dark font-weight-medium" style="padding-bottom: 32px; padding-top: 24px;">Fill Patient Details</h2>
							</div>
							<div class="row">
								<form method="post" name="form1">
                                    {% csrf_token %}
									<div class="form-body">
                                        <label for="id_p_first_name">Name </label>
                                        <div class="row">
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <input type="text" class="form-control" name="p_first_name" id="id_p_first_name" maxlength="120"
                                                        placeholder="First Name"  required/>
                                                </div>
                                            </div>
											<div class="col-md-4">
                                                <div class="form-group">
                                                    <input type="text" class="form-control" name="p_middle_name" maxlength="120"
                                                        placeholder="Middle Name">
                                                </div>
											</div>
											<div class="col-md-4">
                                                <div class="form-group">
                                                    <input type="text" class="form-control" name="p_last_name" id="id_p_last_name" maxlength="100"
                                                        placeholder="Last Name" required>
                                                </div>
											</div>
										</div>
										<div class="form-body" style="padding-top: 20px;">
                                        <div class="row">
                                            <div class="col-md-6">
												<label for="id_p_age">Age</label>
                                                <div class="form-group">
													<input type="text" class="form-control" name="p_age" id="id_p_age" placeholder="Enter Age" required/>
												</div>
                                            </div>
											<div class="col-md-6">
												<label style="padding-bottom: 8px;">Gender</label>
                                                <div class="form-group">
                                                    <div class="form-check form-check-inline" style="padding-right:8px;">
														<input class="form-check-input" type="radio" name="gender"
															id="inlineRadio1" value="Male" required>
														<label class="form-check-label font-weight-light" for="inlineRadio1">Male</label>
													</div>
													<div class="form-check form-check-inline" style="padding-right: 8px;">
														<input class="form-check-input" type="radio" name="gender"
															id="inlineRadio2" value="Female" required>
														<label class="form-check-label font-weight-light" for="inlineRadio2">Female</label>
													</div>
													<div class="form-check form-check-inline">
														<input class="form-check-input" type="radio" name="gender"
															id="inlineRadio3" value="Others" required>
														<label class="form-check-label font-weight-light" for="inlineRadio3">Others</label>
													</div>
                                                </div>
											</div>
										</div>
										<div class="form-body" style="padding-top: 24px;">
											<div class="row">
												<div class="col-lg-6">
													<label for="id_p_email">Email</label>
													<div class="form-group">
														<input type="email" class="form-control" name="p_email" id="id_p_email" placeholder="abc@example.com" required>
													</div>
												</div>
												<div class="col-lg-6">
													<label for="id_p_contact_no">Contact Number</label>
													<div class="form-group">
														<input type="text" class="form-control" name="p_contact_no" id="id_p_contact_no" maxlength="10" minlength="10"  placeholder="Enter Mobile Number" required>
													</div>
												</div>
											</div>
										</div>
										<div class="form-body" style="padding-top: 24px;">
											<div class="row">
												<div class="col-lg-12">
													<label for="id_visit_reason">Reason of Visit</label>
													<div class="form-group">
														<textarea class="form-control" rows="2" id="id_visit_reason" name="visit_reason" id="id_visit_reason" placeholder="Text Here..."></textarea>
													</div>
												</div>
											</div>
										</div>
									<div class="form-actions" style="margin-top: 40px;">
                                        <div class="text-left">
                                            <button type="button" class="btn btn-info" onclick="populate()">Self</button>
                                            <button type="submit" class="btn btn-info">Book</button>
                                            <button type="reset" class="btn btn-info">Reset</button>
                                        </div>
                                    </div>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>

    {% else %}

            <h5>You are not authorized here!</h5>

         {% endif %}

    {% endif %}

    </div>
{% endblock context %}

finalYearProject/patient_app/templates/reviews.html
{% extends "base.html" %}

{% block title %}
    View
{% endblock title %}

{% block context %}

    <div class="container-fluid" style="margin-top: -72px;">

    {% if user.is_authenticated %}

        {% if user.is_patient %}

                 {% if appointment %}

                     <div class="card">
						<div class="card-body" style="margin-left: 32px; padding-bottom:80px;">
							<div class="row">
								<h2 class="text-dark font-weight-medium" style="padding-bottom: 40px; padding-top: 24px;">Write a Review for Dr. {{ doctor.user.first_name }} {{ doctor.user.last_name }}</h2>
							</div>
							<div class="row">
								<form method="post">
                                    {% csrf_token %}
									<div>
										<label for="id_review">Leave your feedback here:</label>
										<textarea class="form-control" rows="3" name="review" id="id_review" placeholder="Text Here..." style="width:800px;" required></textarea>
									</div>
									<div class="form-actions" style="padding-top:40px;">
                                        <div class="text-left">
                                            <button type="submit" class="btn btn-info">Submit</button>
                                            <button type="reset" class="btn btn-link">Reset</button>
                                        </div>
                                    </div>
								</form>
							</div>
						</div>
					</div>

                    {% else %}

                     You can't give reviews!

                 {% endif %}

        {% else %}

            <h5>You are not authorized here!</h5>

        {% endif %}

    {% endif %}

    </div>

{% endblock context %}